### ISSUE TITLE
[FEATURE] Add support for `exec` health and readiness checks

### ISSUE THREAD

**Issue by astromechza** [score-spec/spec#113]
### Detailed description

The existing http probe checks are useful but not all container runtimes support them (for example, docker compose, etc..). A command-based probe is often more generic and easier to configure correctly.

### Context

Score-compose cannot perform http health checks on containers or services.

### Possible implementation

```
execProbe:
  type: object
  additionalProperties: false
  required: [command]
  properties:
    command:
      type: array
      items:
        type: string
```

Also a good idea to add to the existing `containerProbe` spec:

- intervalSeconds: the time in seconds between executions of the probe

(there are lots of other possibe fields here too but we want to keep things simple)
