### ISSUE TITLE
Validation of fields is nearly non-existent

### ISSUE THREAD

**Issue by fernando-villalba** [score-spec/spec#21]
This works and it shouldn't (look at the protocol)

```yaml
apiVersion: score.dev/v1b1
metadata:
  name: frontend
containers:
  frontend:
    image: nginx:alpine
service:
  ports:
    www:
      port: 80
      protocol: Godzilla-growls-angry
      targetPort: 80
```
Translates with score-helm to:

```yaml
containers:
  frontend:
    image:
      name: nginx:alpine
service:
  ports:
    - name: www
      port: 80
      protocol: Godzilla-growls-angry
      targetPort: 80
  type: ClusterIP
```

This also "works"

```yaml
apiVersion: score.dev/v1b1
metadata:
  name: frontend
container-with-massive-angry-typo:
  frontend:
    image: nginx:alpine
service:
  ports:
    www:
      port: 80
      protocol: Godzilla-growls-angry
      targetPort: 80
```

Outputs this:

```yaml
containers: {}
service:
  ports:
    - name: www
      port: 80
      protocol: Godzilla-growls-angry
      targetPort: 80
  type: ClusterIP
```

And it doesn't error at all, there is no validation as it exists with 0 status
