### ISSUE TITLE
score reference livenessProbe docs do not match spec

### ISSUE THREAD

**Issue by aknauf** [score-spec/spec#45]
### Description

In the [score reference docs, containers section](https://docs.score.dev/docs/reference/score-spec-reference/#container-definition), the livenessProbe and readinessProbe doce do not match the example.

The spec section I refer to is as follows:
```
livenessProbe: ContainerProbeSpec
  scheme: string
  host: string
  port: int
  path: string
  httpHeaders:
      name: string
      value: string
readinessProbe: ContainerProbeSpec
  scheme: string
  host: string
  port: int
  path: string
  httpHeaders:
      name: string
      value: string
```

The description refers to an element called `httpGet`, which appears not to exist? It is almost like it is implicit, but if so, is there any value in mentioning it at all? 

Also half of the other keys are not mentioned in the description. They might be self-explanatory, but it would be good to know which are optional and which are required.
