### ISSUE TITLE
[FEATURE] `emptyDir` `Volume` support

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/spec#58]
### Detailed description

Using an `emptyDir` `Volume` via my Score manifest is not supported today.

### Context

Here is my Score manifest:
```
apiVersion: score.dev/v1b1
metadata:
  name: nginx
containers:
  nginx:
    image: nginxinc/nginx-unprivileged:latest
    volumes:
    - source: ${resources.tmp}
      target: /tmp
resources:
  tmp:
    type: emptyDir
```
I can deploy it in Humanitec, but there I'm getting this error attached:
![image](https://user-images.githubusercontent.com/11720844/234956149-9ce17962-51fb-430a-b025-692fa8c65caa.png)

### Possible implementation

The associated Humanitec manifest generated has:
```
        "externals": {
          "tmp": {
            "type": "emptyDir"
          }
        }
```
I can see that there is a difference if I add this emptyDir via the UI where this section is instead under:
```
        "volumes": {
          "tmp": {
            "type": "emptyDir"
          }
        }
```

### Additional information

[Score specification reference - Reserved resource type](https://docs.score.dev/docs/reference/score-spec-reference/#reserved-resource-types).

**Comment by mathieu-benoit** [comment]
As a workaround and if using Humanitec, you can use the Humanitec Score extension, see example below:
```
apiVersion: humanitec.org/v1b1
profile: humanitec/default-module
spec:
  containers:
    nginx-secured:
      volume_mounts:
        /tmp:
          id: volumes.tmp
          read_only: false
  volumes:
    tmp:
      type: emptyDir
```
