### ISSUE TITLE
Load files from disk instead of inline

### ISSUE THREAD

**Issue by sujaya-sys** [score-spec/spec#63]
### Detailed description

This is more of a “we should think about this” rather than a bug, an annoyance so low importance at this point

In score, if you’d like to configure files for your container you do

```
    files:
      - target: /etc/loki/loki-config.yaml
        mode: "644"
        content:
          - |
            auth_enabled: false
            xxx
```

This is good, however…

I have files that are 2-3k lines.

Could we possibly have the option to do:
```

files:
 - target: /etc/loki/loki-config.yaml
 mode: "644"
 source: files/loki-config.yaml
```
