### ISSUE TITLE
[FEATURE] secret support

### ISSUE THREAD

**Issue by garthy** [score-spec/spec#76]
### Detailed description

It would be nice if secrets were supported as a first class resource.  They could be generated and stored then used to create/access the resource and be passed around securely as well as the platform supports and stop writing them to state/config files. eg:- docker-compose output snippit 
```
    workload-one-example:
        command:
            - -c
            - while true; do echo $${CONNECTION}; sleep 5; done
        depends_on:
            wait-for-resources:
                condition: service_started
                required: false
        entrypoint:
            - /bin/sh
        environment:
            CONNECTION: redis://default:XfygjA6Kxtb6mfXZ@redis-FUxtcv:6379
        hostname: workload-one
        image: busybox

```

### Context

secure deployment and configuration and stop secrets getting wrtitten into files and environments

### Possible implementation

using docker(-compose) secrets/k8s secrets a secret could be created
Then used to create and protect the resource
And then used to access the resource.
